from microbit import *
import music
import superbit
import microbit

display.show(Image.HAPPY)

while True:
    music.play('E4:4')
    superbit.motor_control(superbit.M1, 255, 0)
    superbit.motor_control(superbit.M3, 255, 0)
    music.play('E4:4')
    superbit.motor_control(superbit.M1, 255, 0)
    superbit.motor_control(superbit.M3, 255, 0)
    music.play('F4:4')
    superbit.motor_control(superbit.M1, -255, 0)
    superbit.motor_control(superbit.M3, -255, 0)
    music.play('G4:4')
    superbit.motor_control(superbit.M1, -255, 0)
    superbit.motor_control(superbit.M3, -255, 0)
    music.play('G4:4')
    superbit.motor_control(superbit.M1, 255, 0)
    superbit.motor_control(superbit.M3, 255, 0)
    music.play('F4:4')
    superbit.motor_control(superbit.M1, 255, 0)
    superbit.motor_control(superbit.M3, 255, 0)
    music.play('E4:4')
    superbit.motor_control(superbit.M1, 255, 0)
    superbit.motor_control(superbit.M3, 255, 0)
    music.play('D4:4')
    superbit.motor_control(superbit.M1, 255, 0)
    superbit.motor_control(superbit.M3, 255, 0)
    music.play('C4:4')
    superbit.motor_control(superbit.M1, -255, 0)
    superbit.motor_control(superbit.M3, -255, 0)
    music.play('C4:4')
    superbit.motor_control(superbit.M1, -255, 0)
    superbit.motor_control(superbit.M3, -255, 0)
    music.play('D4:4')
    superbit.motor_control(superbit.M1, -255, 0)
    superbit.motor_control(superbit.M3, -255, 0)
    music.play('E4:4')
    superbit.motor_control(superbit.M1, -255, 0)
    superbit.motor_control(superbit.M3, -255, 0)
    music.play('E4:8')
    superbit.motor_control(superbit.M1, 255, 0)
    superbit.motor_control(superbit.M3, 255, 0)
    music.play('D4:4')
    superbit.motor_control(superbit.M1, 255, 0)
    superbit.motor_control(superbit.M3, 255, 0)
    music.play('D4:4')
    superbit.motor_control(superbit.M1, 255, 0)
    superbit.motor_control(superbit.M3, 255, 0)
    microbit.sleep(500)
    music.play('E4:4')
    superbit.motor_control(superbit.M1, -255, 0)
    superbit.motor_control(superbit.M3, -255, 0)
    music.play('E4:4')
    superbit.motor_control(superbit.M1, -255, 0)
    superbit.motor_control(superbit.M3, -255, 0)
    music.play('F4:4')
    superbit.motor_control(superbit.M1, -255, 0)
    superbit.motor_control(superbit.M3, -255, 0)
    music.play('G4:4')
    superbit.motor_control(superbit.M1, -255, 0)
    superbit.motor_control(superbit.M3, -255, 0)
    music.play('G4:4')
    superbit.motor_control(superbit.M1, 255, 0)
    superbit.motor_control(superbit.M3, 255, 0)
    music.play('F4:4')
    superbit.motor_control(superbit.M1, 255, 0)
    superbit.motor_control(superbit.M3, 255, 0)
    music.play('E4:4')
    superbit.motor_control(superbit.M1, 255, 0)
    superbit.motor_control(superbit.M3, 255, 0)
    music.play('D4:4')
    superbit.motor_control(superbit.M1, 255, 0)
    superbit.motor_control(superbit.M3, 255, 0)
    music.play('C4:4')
    superbit.motor_control(superbit.M1, -255, 0)
    superbit.motor_control(superbit.M3, -255, 0)
    music.play('C4:4')
    superbit.motor_control(superbit.M1, -255, 0)
    superbit.motor_control(superbit.M3, -255, 0)
    music.play('D4:4')
    superbit.motor_control(superbit.M1, -255, 0)
    superbit.motor_control(superbit.M3, -255, 0)
    music.play('E4:4')
    superbit.motor_control(superbit.M1, 255, 0)
    superbit.motor_control(superbit.M3, 255, 0)
    music.play('D4:8')
    superbit.motor_control(superbit.M1, 255, 0)
    superbit.motor_control(superbit.M3, 255, 0)
    music.play('C4:4')
    superbit.motor_control(superbit.M1, -255, 0)
    superbit.motor_control(superbit.M3, -255, 0)
    music.play('C4:4')
    superbit.motor_control(superbit.M1, -255, 0)
    superbit.motor_control(superbit.M3, -255, 0)
    microbit.sleep(1000)






